["1.21.11-fabric"]
loom.platform="fabric"
fabric_loader_version="0.17.3"
fabric_api_version="0.139.4+1.21.11"
mc_version_range="1.21.11"
modmenu_version="17.0.0-beta.1"

["1.21.11-neoforge"]
loom.platform="neoforge"
neoforge_version="21.11.31-beta"
mc_version_range="1.21.11"

["26.1-fabric"]
loom.platform="fabric"
fabric_loader_version="0.18.4"
fabric_api_version="0.144.0+26.1"
mc_version_range="26.1,26.1.1"
modmenu_version="18.0.0-alpha.6"

["26.1-neoforge"]
loom.platform="neoforge"
neoforge_version="26.1.0.1-beta"
mc_version_range="26.1,26.1.1"

["26.2-fabric"]
loom.platform="fabric"
fabric_loader_version="0.19.2"
fabric_api_version="0.148.3+26.2"
mc_version_range="26.2"
modmenu_version="20.0.0-beta.2"

["26.2-neoforge"]
loom.platform="neoforge"
neoforge_version="26.2.0.45-beta"
mc_version_range="26.2"

["26.3-fabric"]
loom.platform="fabric"
fabric_loader_version="0.19.3"
fabric_api_version="0.155.3+26.3"
mc_version_range="26.3"